ALTER TABLE Admins ADD ResetToken NVARCHAR(MAX) NULL;
ALTER TABLE Admins ADD ResetTokenExpiry DATETIME2 NULL;
ALTER TABLE Admins ADD OtpCode NVARCHAR(10) NULL;
ALTER TABLE Admins ADD OtpExpiry DATETIME2 NULL;
ALTER TABLE Admins ADD OtpVerified BIT NOT NULL DEFAULT 0;
GO
